/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/v74LHBCWh7D
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Comfortaa } from 'next/font/google'

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { SVGProps } from "react"

export function Collection() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-background">
      <main className="flex-1 p-4 md:p-6 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-6">
        <div className="bg-card rounded-lg overflow-hidden shadow-sm transition-all hover:shadow-md">
          <Link href="#" className="block" prefetch={false}>
            <img
              src="/placeholder.svg"
              alt="NFT 1"
              width="300"
              height="300"
              className="w-full h-60 object-cover"
              style={{ aspectRatio: "300/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold text-card-foreground">Crypto Punk #1234</h3>
              <div className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground">Bid: 0.5 ETH</p>
                <p className="text-sm text-muted-foreground">Ask: 0.7 ETH</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">TVL: $10,000</p>
                <p className="text-sm text-muted-foreground">Total Trades: 100</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">Total Volume: $50,000</p>
                <p className="text-sm text-muted-foreground">Offer TVL: $5,000</p>
              </div>
            </div>
          </Link>
        </div>
        <div className="bg-card rounded-lg overflow-hidden shadow-sm transition-all hover:shadow-md">
          <Link href="#" className="block" prefetch={false}>
            <img
              src="/placeholder.svg"
              alt="NFT 2"
              width="300"
              height="300"
              className="w-full h-60 object-cover"
              style={{ aspectRatio: "300/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold text-card-foreground">Crypto Punk #5678</h3>
              <div className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground">Bid: 0.7 ETH</p>
                <p className="text-sm text-muted-foreground">Ask: 0.9 ETH</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">TVL: $15,000</p>
                <p className="text-sm text-muted-foreground">Total Trades: 150</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">Total Volume: $75,000</p>
                <p className="text-sm text-muted-foreground">Offer TVL: $7,500</p>
              </div>
            </div>
          </Link>
        </div>
        <div className="bg-card rounded-lg overflow-hidden shadow-sm transition-all hover:shadow-md">
          <Link href="#" className="block" prefetch={false}>
            <img
              src="/placeholder.svg"
              alt="NFT 3"
              width="300"
              height="300"
              className="w-full h-60 object-cover"
              style={{ aspectRatio: "300/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold text-card-foreground">Crypto Punk #9012</h3>
              <div className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground">Bid: 0.9 ETH</p>
                <p className="text-sm text-muted-foreground">Ask: 1.1 ETH</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">TVL: $20,000</p>
                <p className="text-sm text-muted-foreground">Total Trades: 200</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">Total Volume: $100,000</p>
                <p className="text-sm text-muted-foreground">Offer TVL: $10,000</p>
              </div>
            </div>
          </Link>
        </div>
        <div className="bg-card rounded-lg overflow-hidden shadow-sm transition-all hover:shadow-md">
          <Link href="#" className="block" prefetch={false}>
            <img
              src="/placeholder.svg"
              alt="NFT 4"
              width="300"
              height="300"
              className="w-full h-60 object-cover"
              style={{ aspectRatio: "300/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold text-card-foreground">Crypto Punk #3456</h3>
              <div className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground">Bid: 0.6 ETH</p>
                <p className="text-sm text-muted-foreground">Ask: 0.8 ETH</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">TVL: $12,000</p>
                <p className="text-sm text-muted-foreground">Total Trades: 120</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">Total Volume: $60,000</p>
                <p className="text-sm text-muted-foreground">Offer TVL: $6,000</p>
              </div>
            </div>
          </Link>
        </div>
        <div className="bg-card rounded-lg overflow-hidden shadow-sm transition-all hover:shadow-md">
          <Link href="#" className="block" prefetch={false}>
            <img
              src="/placeholder.svg"
              alt="NFT 5"
              width="300"
              height="300"
              className="w-full h-60 object-cover"
              style={{ aspectRatio: "300/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold text-card-foreground">Crypto Punk #7890</h3>
              <div className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground">Bid: 0.8 ETH</p>
                <p className="text-sm text-muted-foreground">Ask: 1.0 ETH</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">TVL: $18,000</p>
                <p className="text-sm text-muted-foreground">Total Trades: 180</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">Total Volume: $90,000</p>
                <p className="text-sm text-muted-foreground">Offer TVL: $9,000</p>
              </div>
            </div>
          </Link>
        </div>
        <div className="bg-card rounded-lg overflow-hidden shadow-sm transition-all hover:shadow-md">
          <Link href="#" className="block" prefetch={false}>
            <img
              src="/placeholder.svg"
              alt="NFT 6"
              width="300"
              height="300"
              className="w-full h-60 object-cover"
              style={{ aspectRatio: "300/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold text-card-foreground">Crypto Punk #2468</h3>
              <div className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground">Bid: 0.4 ETH</p>
                <p className="text-sm text-muted-foreground">Ask: 0.6 ETH</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">TVL: $8,000</p>
                <p className="text-sm text-muted-foreground">Total Trades: 80</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">Total Volume: $40,000</p>
                <p className="text-sm text-muted-foreground">Offer TVL: $4,000</p>
              </div>
            </div>
          </Link>
        </div>
        <div className="bg-card rounded-lg overflow-hidden shadow-sm transition-all hover:shadow-md">
          <Link href="#" className="block" prefetch={false}>
            <img
              src="/placeholder.svg"
              alt="NFT 7"
              width="300"
              height="300"
              className="w-full h-60 object-cover"
              style={{ aspectRatio: "300/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold text-card-foreground">Crypto Punk #1357</h3>
              <div className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground">Bid: 0.3 ETH</p>
                <p className="text-sm text-muted-foreground">Ask: 0.5 ETH</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">TVL: $6,000</p>
                <p className="text-sm text-muted-foreground">Total Trades: 60</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">Total Volume: $30,000</p>
                <p className="text-sm text-muted-foreground">Offer TVL: $3,000</p>
              </div>
            </div>
          </Link>
        </div>
        <div className="bg-card rounded-lg overflow-hidden shadow-sm transition-all hover:shadow-md">
          <Link href="#" className="block" prefetch={false}>
            <img
              src="/placeholder.svg"
              alt="NFT 8"
              width="300"
              height="300"
              className="w-full h-60 object-cover"
              style={{ aspectRatio: "300/300", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold text-card-foreground">Crypto Punk #8642</h3>
              <div className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground">Bid: 0.5 ETH</p>
                <p className="text-sm text-muted-foreground">Ask: 0.7 ETH</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">TVL: $10,000</p>
                <p className="text-sm text-muted-foreground">Total Trades: 100</p>
              </div>
              <div className="flex justify-between items-center mt-2">
                <p className="text-sm text-muted-foreground">Total Volume: $50,000</p>
                <p className="text-sm text-muted-foreground">Offer TVL: $5,000</p>
              </div>
            </div>
          </Link>
        </div>
      </main>
    </div>
  )
}

function SearchIcon(props : SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
