import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Providers from "@/Providers";
import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'
import { config } from "@/wagmiConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mintory.fun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    config,
    headers().get('cookie')
  )
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>
          <Navbar />
          <div className="pt-20">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
