/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RkvN0yBZJF3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { SVGProps } from "react"

export function Create() {
  return (
    <div className="min-h-screen  text-white p-8">
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center mb-8">
          <ArrowLeftIcon className="w-6 h-6 mr-2 text-black" />
          <h1 className="text-xl font-bold text-black">create project</h1>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <div className="mb-4">
              <label htmlFor="project-name" className="block mb-2 text-sm font-medium text-black">
                project name
              </label>
              <Input
                id="project-name"
                placeholder="your project's name"
                className="w-full bg-gray-100 border-gray-200 text-gray-500"
              />
            </div>
            <div className="mb-4">
              <label htmlFor="chain" className="block mb-2 text-sm font-medium text-black">
                chain
              </label>
              <Select>
                <SelectTrigger id="chain" className="w-full bg-gray-100 border-gray-200 placeholder:text-muted-foreground text-muted-foreground">
                  <SelectValue placeholder="Base" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="base">Base</SelectItem>
                  <SelectItem value="optimism">Optimism</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <a href="#" className="text-sm text-gray-400 underline mb-4 block">
              see more options
            </a>
            <Button className="w-full bg-purple-600 hover:bg-purple-700">create project</Button>
          </div>
          <div className="flex items-center justify-center border-2 border-dashed border-gray-700 rounded-lg p-8">
            <div className="text-center">
              <PlusIcon className="w-8 h-8 mb-4 text-black" />
              <p className="text-sm mb-2">click to add files</p>
              <p className="text-xs text-gray-400 mb-2">or drag & drop media</p>
              <p className="text-xs text-gray-400">jpg, png, mp4, gif or svg</p>
              <p className="text-xs text-gray-400">1000x1000px recommended.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function ArrowLeftIcon(props : SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function PlusIcon(props : SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function WalletIcon(props : SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" />
      <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />
    </svg>
  )
}
