/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RkvN0yBZJF3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function Create() {
  return (
    <div className="min-h-screen bg-black text-white p-8">
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center mb-8">
          <ArrowLeftIcon className="w-6 h-6 mr-2" />
          <h1 className="text-xl font-bold">create project</h1>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <div className="mb-4">
              <label htmlFor="project-name" className="block mb-2 text-sm font-medium">
                project name
              </label>
              <Input
                id="project-name"
                placeholder="your project's name"
                className="w-full bg-gray-800 border-gray-700"
              />
            </div>
            <div className="mb-4">
              <label htmlFor="chain" className="block mb-2 text-sm font-medium">
                chain
              </label>
              <Select>
                <SelectTrigger id="chain" className="w-full bg-gray-800 border-gray-700">
                  <SelectValue placeholder="Base" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="base">Base</SelectItem>
                  <SelectItem value="ethereum">Ethereum</SelectItem>
                  <SelectItem value="polygon">Polygon</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-4 mb-4">
              <div>
                <label htmlFor="price" className="block mb-2 text-sm font-medium">
                  price
                </label>
                <div className="flex items-center bg-gray-800 border border-gray-700 p-2 rounded">
                  <span className="text-sm">0.000577</span>
                  <span className="ml-2 text-sm">ETH</span>
                </div>
              </div>
              <div>
                <label htmlFor="end-date" className="block mb-2 text-sm font-medium">
                  end date
                </label>
                <Select>
                  <SelectTrigger id="end-date" className="w-full bg-gray-800 border-gray-700">
                    <SelectValue placeholder="7 days" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="7-days">7 days</SelectItem>
                    <SelectItem value="14-days">14 days</SelectItem>
                    <SelectItem value="30-days">30 days</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <p className="text-xs text-gray-400 mb-4">
              minters will pay 0.000577 ETH per mint: 0.000577 + 0.000200 protocol fee. proceeds from your projects show
              in <WalletIcon className="inline w-4 h-4" /> balance
            </p>
            <a href="#" className="text-sm text-gray-400 underline mb-4 block">
              see more options
            </a>
            <Button className="w-full bg-purple-600 hover:bg-purple-700">create project</Button>
          </div>
          <div className="flex items-center justify-center border-2 border-dashed border-gray-700 rounded-lg p-8">
            <div className="text-center">
              <PlusIcon className="w-8 h-8 mb-4" />
              <p className="text-sm mb-2">click to add files</p>
              <p className="text-xs text-gray-400 mb-2">or drag & drop media</p>
              <p className="text-xs text-gray-400">jpg, png, mp4, gif or svg</p>
              <p className="text-xs text-gray-400">1000x1000px recommended.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function WalletIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" />
      <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />
    </svg>
  )
}
